
# Google cloud
HWConfig:

    # for depthwise
    hx: 7 # has to be atleast Kx, Kx+Sx, and so on ..
    wx: 6 # has to be atleast Ky, Ky + Sy and so on ..
    cx: 128

    # for pointwise
    fx: 128
    hxx: 7
    wxx: 6
    cxx: 128
    padd_unit: 256
    # mac = (wxx-3+1)*cxx*fx
    dma_cycles: 0.112680288
    mac_cycles: 1
    padd_cycles: 1



